
num_rounds: 10
num_clients: 6
batch_size: 10
num_classes: 10
num_clients_per_round_fit: 3
num_clients_per_round_eval: 4
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
num_cpus: 2
num_gpus: 0.5