
num_rounds: 5
num_clients: 4
batch_size: 8
num_classes: 10
num_clients_per_round_fit: 4
num_clients_per_round_eval: 4
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
num_cpus: 4  #4
num_gpus: 0.5  #0.5