
num_rounds: 10
num_clients: 10
batch_size: 16
num_classes: 10
#num_clients_per_round_fit: 10
#num_clients_per_round_eval: 10
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
num_cpus: 8  #4
num_gpus: 1  #0.5